[variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
SESSION_DRIVER = "database"
CACHE_STORE = "database"
QUEUE_CONNECTION = "database"
FILESYSTEM_DISK = "local"
NIXPACKS_PHP_ROOT_DIR = "/app/public"
NIXPACKS_PHP_FALLBACK_PATH = "/index.php"
NIXPACKS_NODE_VERSION = "22"
