<?php

return [
    [
        'slug' => 'has-dalam-sapi',
        'name' => 'Has Dalam Sapi',
        'category' => 'Daging Sapi',
        'price' => 145000,
        'unit' => '/kg',
        'badge' => 'Fresh Frozen',
        'image' => 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Potongan premium untuk steak dan masakan restoran dengan tekstur lembut.',
    ],
    [
        'slug' => 'short-plate-sapi',
        'name' => 'Short Plate Sapi',
        'category' => 'Daging Sapi',
        'price' => 132000,
        'unit' => '/kg',
        'badge' => 'Best Seller',
        'image' => 'https://images.unsplash.com/photo-1615937691194-97dbd3f3dc29?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Cocok untuk grill, yakiniku, dan menu irisan tipis untuk usaha kuliner.',
    ],
    [
        'slug' => 'dada-ayam-fillet',
        'name' => 'Dada Ayam Fillet',
        'category' => 'Daging Ayam',
        'price' => 52000,
        'unit' => '/kg',
        'badge' => 'Halal',
        'image' => 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Fillet ayam siap olah untuk menu crispy, grilled, dan catering harian.',
    ],
    [
        'slug' => 'paha-bawah-ayam',
        'name' => 'Paha Bawah Ayam',
        'category' => 'Daging Ayam',
        'price' => 47000,
        'unit' => '/kg',
        'badge' => 'Ready Stock',
        'image' => 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Pilihan ekonomis untuk fried chicken dan menu paket usaha cepat saji.',
    ],
    [
        'slug' => 'fillet-dori',
        'name' => 'Fillet Dori',
        'category' => 'Ikan & Seafood',
        'price' => 63000,
        'unit' => '/kg',
        'badge' => 'Premium',
        'image' => 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Fillet ikan lembut minim duri, cocok untuk menu fish and chips dan rice bowl.',
    ],
    [
        'slug' => 'udang-kupas',
        'name' => 'Udang Kupas',
        'category' => 'Ikan & Seafood',
        'price' => 98000,
        'unit' => '/kg',
        'badge' => 'Frozen',
        'image' => 'https://images.unsplash.com/photo-1565680018434-b513d7f756f0?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Udang kupas bersih siap masak untuk menu tumis, tepung, dan bento.',
    ],
    [
        'slug' => 'chicken-nugget',
        'name' => 'Chicken Nugget',
        'category' => 'Produk Olahan',
        'price' => 32000,
        'unit' => '/pack',
        'badge' => 'Favorite',
        'image' => 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Nugget favorit keluarga, cocok untuk retail dan kebutuhan frozen food rumahan.',
    ],
    [
        'slug' => 'bakso-sapi',
        'name' => 'Bakso Sapi',
        'category' => 'Produk Olahan',
        'price' => 38000,
        'unit' => '/pack',
        'badge' => 'Best Seller',
        'image' => 'https://images.unsplash.com/photo-1600673877822-f2b59f3d4eea?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Bakso sapi padat daging dengan rasa gurih, ideal untuk kuah dan tumisan.',
    ],
    [
        'slug' => 'saos-bbq',
        'name' => 'Saus BBQ',
        'category' => 'Bumbu & Pelengkap',
        'price' => 18000,
        'unit' => '/botol',
        'badge' => 'Support',
        'image' => 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Saus pendamping untuk menu grill dan roast dengan rasa smoky-manis.',
    ],
    [
        'slug' => 'kaldu-bubuk',
        'name' => 'Kaldu Bubuk',
        'category' => 'Bumbu & Pelengkap',
        'price' => 12000,
        'unit' => '/pack',
        'badge' => 'Support',
        'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Pelengkap dapur untuk konsistensi rasa pada menu sup dan tumisan.',
    ],
    [
        'slug' => 'dimsum-ayam',
        'name' => 'Dimsum Ayam',
        'category' => 'Produk Olahan',
        'price' => 29000,
        'unit' => '/pack',
        'badge' => 'Ready Stock',
        'image' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Dimsum praktis untuk menu snack atau paket usaha kuliner.',
    ],
    [
        'slug' => 'custom-potong',
        'name' => 'Custom Potong',
        'category' => 'Custom Request',
        'price' => 0,
        'unit' => '/request',
        'badge' => 'By Order',
        'image' => 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=1200&q=80',
        'description' => 'Layanan potong dan kemasan khusus sesuai kebutuhan operasional mitra usaha.',
    ],
];
